/** Info 패널 스타일. 값은 tokens 에서만 가져온다. */
import { tokens } from '../../../styles/tokens';

const { color, font, fontSize, fontWeight, space } = tokens;

export const infoStyles = {
  root: {
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    fontFamily: font.sans,
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    padding: '10px 12px',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  sectionTitle: {
    fontSize: fontSize['11'],
    fontWeight: fontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },
  sectionSubtitle: {
    marginLeft: 'auto',
    fontSize: '10.5px',
    fontFamily: font.mono,
    letterSpacing: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: '120px',
  },
  sectionBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: space['2'],
    minHeight: '20px',
    fontSize: fontSize['12'],
  },
  rowLabel: {
    flexShrink: 0,
    minWidth: '64px',
    fontSize: '11px',
    letterSpacing: '0.02em',
    color: 'var(--ui-subtext)',
  },
  rowValue: {
    flex: 1,
    minWidth: 0,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    color: 'var(--ui-text)',
  },
  rowValueText: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  rowValueMono: {
    fontFamily: font.mono,
    fontSize: '11.5px',
    letterSpacing: 0,
  },
  copyBtn: {
    flexShrink: 0,
    width: '18px',
    height: '18px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    color: 'var(--ui-subtext)',
    padding: 0,
    borderRadius: '3px',
    transition: 'color 120ms',
  },
  note: {
    fontSize: '10.5px',
    color: 'var(--ui-accent)',
    opacity: 0.85,
    lineHeight: 1.4,
    paddingTop: '2px',
  },
  statRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    paddingTop: '2px',
    paddingBottom: '2px',
  },
  statHeader: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: space['2'],
  },
  statLabel: {
    fontSize: '11px',
    fontWeight: fontWeight.semibold,
    color: 'var(--ui-subtext)',
    letterSpacing: '0.04em',
  },
  statRight: {
    fontFamily: font.mono,
    fontSize: '10.5px',
    color: 'var(--ui-subtext)',
    letterSpacing: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    minWidth: 0,
  },
  barTrack: {
    width: '100%',
    height: '6px',
    background: 'var(--ui-crust)',
    borderRadius: '3px',
    overflow: 'hidden',
    border: '1px solid var(--ui-border)',
  },
  barFill: {
    height: '100%',
    borderRadius: '3px',
    transition: 'width 600ms cubic-bezier(0.16, 1, 0.3, 1), background 200ms',
  },
  stackTrack: {
    width: '100%',
    height: '8px',
    display: 'flex',
    gap: '1px',
    background: 'var(--ui-crust)',
    borderRadius: '4px',
    overflow: 'hidden',
    border: '1px solid var(--ui-border)',
  },
  stackSegment: {
    height: '100%',
    minWidth: '1px',
    transition: 'width 600ms cubic-bezier(0.16, 1, 0.3, 1)',
  },
  stackLegend: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '6px',
    fontSize: '9.5px',
    color: 'var(--ui-subtext)',
    fontFamily: font.mono,
  },
  legendItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '3px',
  },
  legendDot: {
    width: '6px',
    height: '6px',
    borderRadius: '2px',
    display: 'inline-block',
    flexShrink: 0,
  },
  processBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1px',
    paddingTop: '3px',
  },
  processHeader: {
    display: 'grid',
    gridTemplateColumns: '1fr auto auto',
    gap: '8px',
    padding: '0 6px 2px',
    fontSize: '10px',
    color: 'var(--ui-subtext)',
    fontWeight: fontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  processError: {
    fontSize: '10px',
    color: 'var(--ui-danger, #f38ba8)',
    padding: '3px 6px',
    background: 'color-mix(in srgb, var(--ui-danger, #f38ba8) 12%, transparent)',
    border: '1px solid color-mix(in srgb, var(--ui-danger, #f38ba8) 35%, transparent)',
    borderRadius: '4px',
    marginBottom: '2px',
  },
  processRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto auto auto',
    alignItems: 'center',
    gap: '6px',
    minHeight: '28px',
    padding: '4px 5px',
    borderRadius: '5px',
    background: 'color-mix(in srgb, var(--ui-surface0) 72%, transparent)',
    border: '1px solid color-mix(in srgb, var(--ui-border) 46%, transparent)',
  },
  processMain: {
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '1px',
  },
  processNameRow: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '6px',
    minWidth: 0,
  },
  processName: {
    fontSize: '11px',
    fontWeight: fontWeight.semibold,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  processMeta: {
    fontFamily: font.mono,
    fontSize: '9px',
    color: 'var(--ui-subtext)',
    flexShrink: 0,
    opacity: 0.7,
  },
  processCmd: {
    fontFamily: font.mono,
    fontSize: '9.5px',
    color: 'var(--ui-subtext)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  processBadge: {
    height: '15px',
    padding: '0 5px',
    borderRadius: '4px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '9px',
    fontWeight: fontWeight.bold,
    color: 'var(--ui-accent)',
    background: 'color-mix(in srgb, var(--ui-accent) 14%, transparent)',
    border: '1px solid color-mix(in srgb, var(--ui-accent) 32%, transparent)',
  },
  processStats: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: '0',
    minWidth: '56px',
    fontFamily: font.mono,
  },
  processCpu: {
    fontSize: '10px',
    color: 'var(--ui-text)',
    fontWeight: fontWeight.semibold,
  },
  processMem: {
    fontSize: '9.5px',
    color: 'var(--ui-subtext)',
  },
  processActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '2px',
    flexShrink: 0,
  },
  processKillBtn: {
    width: '20px',
    height: '20px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    borderRadius: '4px',
    background: 'transparent',
    color: 'var(--ui-subtext)',
    padding: 0,
    transition: 'background 0.12s ease, color 0.12s ease',
  },
};

export default infoStyles;
