/** Info 패널 스타일. 값은 tokens 에서만 가져온다. */
import { tokens } from '../../../styles/tokens';

const { color, font, fontSize, fontWeight, motion, radius, space } = tokens;

export const infoStyles = {
  root: {
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    fontFamily: font.sans,
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    padding: '10px 12px',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  sectionTitle: {
    fontSize: fontSize['11'],
    fontWeight: fontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },
  sectionSubtitle: {
    marginLeft: 'auto',
    fontSize: '10.5px',
    fontFamily: font.mono,
    letterSpacing: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: '120px',
  },
  sectionBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: space['2'],
    minHeight: '20px',
    fontSize: fontSize['12'],
  },
  rowLabel: {
    flexShrink: 0,
    minWidth: '64px',
    fontSize: '11px',
    letterSpacing: '0.02em',
    color: 'var(--ui-subtext)',
  },
  rowValue: {
    flex: 1,
    minWidth: 0,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    color: 'var(--ui-text)',
  },
  rowValueText: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  rowValueMono: {
    fontFamily: font.mono,
    fontSize: '11.5px',
    letterSpacing: 0,
  },
  copyBtn: {
    flexShrink: 0,
    width: '18px',
    height: '18px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    color: 'var(--ui-subtext)',
    padding: 0,
    borderRadius: '3px',
    transition: 'color 120ms',
  },
  note: {
    fontSize: '10.5px',
    color: 'var(--ui-accent)',
    opacity: 0.85,
    lineHeight: 1.4,
    paddingTop: '2px',
  },
  statRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    paddingTop: '2px',
    paddingBottom: '2px',
  },
  statHeader: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: space['2'],
  },
  statLabel: {
    fontSize: '11px',
    fontWeight: fontWeight.semibold,
    color: 'var(--ui-subtext)',
    letterSpacing: '0.04em',
  },
  statRight: {
    fontFamily: font.mono,
    fontSize: '10.5px',
    color: 'var(--ui-subtext)',
    letterSpacing: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    minWidth: 0,
  },
  barTrack: {
    width: '100%',
    height: '6px',
    background: 'var(--ui-crust)',
    borderRadius: '3px',
    overflow: 'hidden',
    border: '1px solid var(--ui-border)',
  },
  barFill: {
    height: '100%',
    borderRadius: '3px',
    transition: 'width 600ms cubic-bezier(0.16, 1, 0.3, 1), background 200ms',
  },
  stackTrack: {
    width: '100%',
    height: '8px',
    display: 'flex',
    gap: '1px',
    background: 'var(--ui-crust)',
    borderRadius: '4px',
    overflow: 'hidden',
    border: '1px solid var(--ui-border)',
  },
  stackSegment: {
    height: '100%',
    minWidth: '1px',
    transition: 'width 600ms cubic-bezier(0.16, 1, 0.3, 1)',
  },
  stackLegend: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '6px',
    fontSize: '9.5px',
    color: 'var(--ui-subtext)',
    fontFamily: font.mono,
  },
  legendItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '3px',
  },
  legendDot: {
    width: '6px',
    height: '6px',
    borderRadius: '2px',
    display: 'inline-block',
    flexShrink: 0,
  },
  processBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: space['0.5'],
    paddingTop: space['1'],
  },
  processHeader: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    gap: space['2'],
    padding: `0 ${space['1.5']} ${space['0.5']}`,
    fontSize: fontSize['10'],
    color: color.subtext,
    fontWeight: fontWeight.semibold,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  processError: {
    fontSize: fontSize['10'],
    color: color.danger,
    padding: `${space['1']} ${space['1.5']}`,
    background: `color-mix(in srgb, ${color.danger} 12%, transparent)`,
    border: `1px solid color-mix(in srgb, ${color.danger} 35%, transparent)`,
    borderRadius: radius.sm,
    marginBottom: space['0.5'],
  },
  processRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto auto',
    alignItems: 'center',
    columnGap: space['1.5'],
    rowGap: space['1'],
    padding: `${space['1']} ${space['1.5']}`,
    borderRadius: radius.sm,
    background: `color-mix(in srgb, ${color.surface0} var(--glass-fill, 72%), transparent)`,
    border: `1px solid color-mix(in srgb, ${color.border} var(--glass-line, 46%), transparent)`,
  },
  processMain: {
    gridColumn: '1 / -1',
    gridRow: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: space['0.5'],
  },
  processNameRow: {
    display: 'flex',
    alignItems: 'baseline',
    gap: space['1.5'],
    minWidth: 0,
  },
  processName: {
    flex: 1,
    minWidth: 0,
    fontSize: fontSize['11'],
    fontWeight: fontWeight.semibold,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  processMeta: {
    fontFamily: font.mono,
    fontSize: fontSize['10'],
    color: color.subtext,
    flexShrink: 0,
    opacity: 0.7,
  },
  processCmd: {
    fontFamily: font.mono,
    fontSize: fontSize['10'],
    color: color.subtext,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  processBadge: {
    gridColumn: 1,
    gridRow: 2,
    justifySelf: 'start',
    height: space['4'],
    padding: `0 ${space['1.5']}`,
    borderRadius: radius.xs,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: fontSize['10'],
    fontWeight: fontWeight.semibold,
    color: color.accent,
    background: `color-mix(in srgb, ${color.accent} 14%, transparent)`,
    border: `1px solid color-mix(in srgb, ${color.accent} 32%, transparent)`,
  },
  processStats: {
    gridColumn: 2,
    gridRow: 2,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: space['1.5'],
    minWidth: 0,
    fontFamily: font.mono,
  },
  processCpu: {
    fontSize: fontSize['10'],
    color: color.text,
    fontWeight: fontWeight.semibold,
  },
  processMem: {
    fontSize: fontSize['10'],
    color: color.subtext,
  },
  processActions: {
    gridColumn: 3,
    gridRow: 2,
    display: 'flex',
    alignItems: 'center',
    gap: space['0.5'],
    flexShrink: 0,
  },
  processKillBtn: {
    width: space['6'],
    height: space['6'],
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    borderRadius: radius.sm,
    background: 'transparent',
    color: color.subtext,
    padding: 0,
    transition: `background ${motion.fast}, color ${motion.fast}`,
  },
};

export default infoStyles;
