const AppStyles = {
  loadingContainer: {
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'fixed',
  },
  loadingLogo: {
    margin: 0,
    fontSize: '28px',
    fontWeight: '700',
    marginBottom: '12px',
    textTransform: 'uppercase',
  },
  loadingText: {
    margin: 0,
    fontSize: '16px',
  },
  container: {
    width: '100vw',
    height: '100vh',
    display: 'flex',
    flexDirection: 'column',
    position: 'fixed',
    top: 0,
    left: 0,
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0',
    flexShrink: 0,
    boxSizing: 'border-box',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    flexWrap: 'nowrap',
    height: '100%',
    paddingLeft: '4px',
    minWidth: 'fit-content',
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '2px',
    height: '100%',
    paddingRight: '4px',
    flex: 1,
    overflow: 'visible',
  },
  hamburgerBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '0 8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '2px',
    transition: 'background-color 0.15s ease',
    height: '100%',
  },
  title: {
    margin: 0,
    textTransform: 'uppercase',
    padding: '0 8px',
    display: 'flex',
    alignItems: 'center',
    height: '100%',
    letterSpacing: '1px',
    fontWeight: '800',
  },
  sessionInfo: {
    fontSize: '11px',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '0 10px',
    height: '24px',
    fontWeight: '700',
    borderRadius: '2px',
  },
  headerBtn: {
    padding: '0 8px',
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    transition: 'all 0.2s ease',
  },
  desktopButtons: {
    display: 'flex',
    height: '100%',
    gap: '2px',
  },
  terminalContainer: {
    flex: 1,
    overflow: 'hidden',
    position: 'relative',
    padding: '12px', // 터미널 안쪽 여백 추가
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    gap: '20px',
    padding: '40px',
  },
  emptyIcon: {
    opacity: 0.5,
  },
  emptyTitle: {
    margin: 0,
    fontSize: '24px',
    fontWeight: '600',
  },
  emptyMessage: {
    margin: 0,
    fontSize: '14px',
    textAlign: 'center',
  },
  emptyButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 20px',
    border: 'none',
    fontSize: '14px',
    fontWeight: '700',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    marginTop: '12px',
    borderRadius: '2px',
  },
  menuOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100vh',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 9998,
  },
  dropdown: {
    position: 'absolute',
    top: 'calc(100% + 4px)',
    right: 0,
    minWidth: '200px',
    zIndex: 9999,
    overflow: 'hidden',
    borderRadius: '2px',
  },
  dropdownItem: {
    padding: '8px 12px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dropdownLabel: {
    fontSize: '12px',
    fontWeight: '500',
  },
  dropdownValue: {
    fontSize: '13px',
  },
  dropdownButton: {
    width: '100%',
    padding: '10px 12px',
    background: 'none',
    border: 'none',
    fontSize: '13px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    transition: 'all 0.15s ease',
    textAlign: 'left',
    lineHeight: '1',
    borderRadius: '2px',
  },
  statusBar: {
    position: 'fixed',
    left: '12px',
    right: '12px',
    height: '32px',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '0 8px',
    overflowX: 'auto',
    zIndex: 9997,
    fontSize: '11px',
    fontFamily: '"JetBrains Mono", monospace',
    scrollbarWidth: 'none',
    borderRadius: '2px',
  },
  statusTab: {
    padding: '0 10px',
    height: '24px',
    display: 'flex',
    alignItems: 'center',
    whiteSpace: 'nowrap',
    cursor: 'pointer',
    transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
    borderRadius: '2px',
  }
};

export default AppStyles;
