import { tokens } from '../../styles/tokens';

const { color, font, fontSize, fontWeight, radius, space, motion } = tokens;

export const fszStyles = {
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    width: '100%',
  },
  input: {
    width: '52px',
    height: '28px',
    padding: '0 6px',
    background: color.crust,
    color: color.text,
    border: `1px solid ${color.border}`,
    borderRadius: radius.sm,
    fontSize: fontSize['12'],
    fontFamily: 'inherit',
    outline: 'none',
    textAlign: 'center',
    flexShrink: 0,
  },
  btn: {
    width: '28px',
    height: '28px',
    background: color.surface0,
    color: color.text,
    border: `1px solid ${color.border}`,
    borderRadius: radius.sm,
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    flexShrink: 0,
    fontFamily: 'inherit',
    lineHeight: 1,
  },
  slider: {
    flex: 1,
    accentColor: color.accent,
    cursor: 'pointer',
    minWidth: 0,
  },
};

export const shortcutStyles = {
  group: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: space['3'],
    minHeight: '26px',
    padding: '4px 6px',
    background: color.surface0,
    border: `1px solid ${color.border}`,
    borderRadius: radius.sm,
  },
  keys: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    flexShrink: 0,
    flexWrap: 'wrap',
  },
  kbd: {
    minHeight: '18px',
    display: 'inline-flex',
    alignItems: 'center',
    padding: '0 6px',
    borderRadius: '5px',
    background: color.mantle,
    border: `1px solid ${color.border}`,
    color: color.text,
    fontFamily: font.mono,
    fontSize: '11px',
    lineHeight: 1,
  },
  desc: {
    minWidth: 0,
    color: color.subtext,
    fontSize: fontSize['12'],
    textAlign: 'right',
    lineHeight: 1.35,
  },
};

export const styles = {
  tabBar: {
    display: 'flex',
    gap: '4px',
    padding: `8px ${space['3']}`,
    borderBottom: `1px solid color-mix(in srgb, var(--ui-border, ${color.border}) 70%, transparent)`,
    background: `color-mix(in srgb, var(--ui-base, ${color.base}) 44%, transparent)`,
    overflowX: 'auto',
    flexShrink: 0,
  },
  tabBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    height: '30px',
    padding: `0 ${space['3']}`,
    background: 'transparent',
    border: `1px solid transparent`,
    borderRadius: radius.sm,
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontSize: fontSize['12'],
    fontWeight: fontWeight.medium,
    transition: `background ${motion.fast}, color ${motion.fast}, border-color ${motion.fast}`,
    flexShrink: 0,
  },
  body: {
    padding: `${space['3']} ${space['4']}`,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: space['2'],
    paddingTop: space['1'],
    paddingBottom: space['1'],
  },
  sectionTitle: {
    fontSize: fontSize['11'],
    fontWeight: fontWeight.medium,
    color: color.muted,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    marginBottom: space['1'],
  },
  sectionBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: space['3'],
  },
  list: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  listRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    minHeight: '44px',
    padding: '8px 10px',
    background: color.surface0,
    border: `1px solid ${color.border}`,
    borderRadius: radius.sm,
    cursor: 'pointer',
    fontFamily: 'inherit',
    color: color.text,
    textAlign: 'left',
    transition: `background ${motion.fast}`,
  },
  listIcon: {
    width: '24px',
    height: '24px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  listText: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '1px',
  },
  listName: {
    fontSize: fontSize['12'],
    fontWeight: fontWeight.semibold,
    color: color.text,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  listSub: {
    fontSize: '10.5px',
    color: color.muted,
    fontFamily: font.mono,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  addRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    minHeight: '44px',
    padding: '8px 10px',
    width: '100%',
    background: color.surface0,
    border: `1px solid ${color.border}`,
    borderRadius: radius.sm,
    cursor: 'pointer',
    fontFamily: 'inherit',
    color: color.text,
    textAlign: 'left',
    marginTop: space['1'],
    transition: `background ${motion.fast}`,
  },
  empty: {
    padding: `${space['4']} 0`,
    fontSize: fontSize['12'],
    color: color.muted,
    textAlign: 'center',
  },
  // 카드 묶음 — 성격이 같은 카드들은 붙여 세우고 사이에 선을 긋지 않는다.
  cardStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: space['2'],
  },
  /* 접히는 구획 = 카드. 글자만 떠 있으면 누를 수 있는지, 어디까지가 한 덩어리인지 모른다. */
  collapseCard: {
    display: 'flex',
    flexDirection: 'column',
    background: color.surface0,
    border: `1px solid ${color.border}`,
    borderRadius: radius.md,
    overflow: 'hidden',
    transition: `border-color ${motion.fast}`,
  },
  collapseCardOpen: {
    borderColor: color.borderStrong,
  },
  collapseHead: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    width: '100%',
    minHeight: '42px',
    padding: `0 ${space['3']}`,
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    textAlign: 'left',
    font: 'inherit',
    transition: `background ${motion.fast}`,
  },
  /* 제목 앞 아이콘 타일 — 카드가 셋 나란히 서면 글자를 읽기 전에 무엇인지 구분돼야 한다.
     앱의 다른 아이콘 타일과 같은 문법(면 + 헤어라인 + 4px 라운드). */
  collapseIcon: {
    width: '22px',
    height: '22px',
    flexShrink: 0,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '5px',
    color: color.subtext,
    background: `color-mix(in srgb, ${color.text} 7%, transparent)`,
    border: `1px solid ${color.border}`,
    boxSizing: 'border-box',
  },
  collapseTitle: {
    fontSize: fontSize['12'],
    fontWeight: fontWeight.medium,
    color: color.text,
    letterSpacing: '0.01em',
  },
  collapseBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: space['2'],
    padding: `${space['1']} ${space['3']} ${space['3']}`,
    // 머리와 본문 사이 헤어라인 — 같은 카드 안이라도 누르는 곳과 읽는 곳은 다르다.
    borderTop: `1px solid ${color.border}`,
    paddingTop: space['3'],
  },
  divider: {
    height: '1px',
    background: color.border,
    margin: `${space['3']} 0`,
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: space['1'],
  },
  label: {
    fontSize: fontSize['12'],
    color: color.subtext,
    fontWeight: fontWeight.medium,
  },
  input: {
    width: '100%',
    height: '32px',
    padding: `0 ${space['3']}`,
    background: color.crust,
    color: color.text,
    border: `1px solid ${color.border}`,
    borderRadius: radius.sm,
    fontSize: fontSize['13'],
    fontFamily: 'inherit',
    outline: 'none',
    transition: `border-color ${motion.fast}`,
  },
  readonly: {
    width: '100%',
    height: '32px',
    padding: `0 ${space['3']}`,
    display: 'flex',
    alignItems: 'center',
    background: color.mantle,
    color: color.subtext,
    border: `1px solid ${color.border}`,
    borderRadius: radius.sm,
    fontSize: fontSize['13'],
    fontFamily: font.mono,
  },
  hint: {
    fontSize: fontSize['11'],
    color: color.muted,
    marginTop: space['0.5'],
  },
  slider: {
    width: '100%',
    accentColor: color.accent,
    cursor: 'pointer',
  },
  toggleRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    cursor: 'pointer',
  },
  toggleLabel: {
    fontSize: fontSize['13'],
    color: color.text,
  },
  toggle: {
    position: 'relative',
    width: '30px',
    height: '16px',
    border: 'none',
    borderRadius: radius.full,
    cursor: 'pointer',
    transition: `background ${motion.fast}`,
    padding: 0,
  },
  toggleKnob: {
    position: 'absolute',
    top: '2px',
    left: '2px',
    width: '12px',
    height: '12px',
    background: '#fff',
    borderRadius: radius.full,
    transition: `transform ${motion.fast}`,
  },
  footer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: `${space['3']} ${space['4']}`,
    borderTop: `1px solid ${color.border}`,
    background: color.mantle,
    flexShrink: 0,
  },
  footerNote: {
    fontSize: fontSize['11'],
    color: color.muted,
  },
  inlineLogoutBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    flexShrink: 0,
    gap: '5px',
    height: '32px',
    padding: `0 ${space['3']}`,
    background: color.surface0,
    border: `1px solid ${color.border}`,
    borderRadius: radius.sm,
    cursor: 'pointer',
    color: color.subtext,
    fontSize: fontSize['12'],
    fontFamily: 'inherit',
    fontWeight: fontWeight.medium,
    transition: `background ${motion.fast}, border-color ${motion.fast}`,
  },
};

