import { tokens } from '../../styles/tokens';

const { color, font, fontSize, fontWeight, radius, space, shadow, motion } = tokens;

export const heStyles = {
  tabBar: {
    display: 'flex',
    gap: '4px',
    padding: `8px ${space['3']}`,
    borderBottom: `1px solid ${color.border}`,
    background: color.mantle,
    flexShrink: 0,
  },
  tabBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    height: '28px',
    padding: `0 10px`,
    background: 'transparent',
    border: `1px solid transparent`,
    borderRadius: radius.sm,
    cursor: 'pointer',
    fontFamily: 'inherit',
    fontSize: fontSize['11'],
    fontWeight: fontWeight.medium,
    transition: `background ${motion.fast}, color ${motion.fast}, border-color ${motion.fast}`,
    flexShrink: 0,
  },
};

export const styles = {
  overlay: {
    position: 'absolute',
    inset: 0,
    background: color.scrim,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10010,
    backdropFilter: 'blur(2px)',
    fontFamily: font.sans,
  },
  modal: {
    width: '92%',
    maxWidth: '480px',
    maxHeight: '88vh',
    background: color.base,
    border: `1px solid ${color.border}`,
    borderRadius: radius.lg,
    boxShadow: shadow.lg,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: `${space['3']} ${space['4']}`,
    borderBottom: `1px solid ${color.border}`,
  },
  title: {
    fontSize: fontSize['14'],
    fontWeight: fontWeight.semibold,
    color: color.text,
  },
  closeBtn: {
    width: '24px',
    height: '24px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'transparent',
    color: color.muted,
    border: 'none',
    borderRadius: radius.xs,
    cursor: 'pointer',
  },
  body: {
    padding: `${space['3']} ${space['4']}`,
    overflowY: 'auto',
  },
  section: { display: 'flex', flexDirection: 'column', gap: space['2'], paddingTop: space['1'], paddingBottom: space['1'] },
  sectionTitle: {
    fontSize: fontSize['11'],
    fontWeight: fontWeight.medium,
    color: color.muted,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    marginBottom: space['1'],
  },
  sectionBody: { display: 'flex', flexDirection: 'column', gap: space['3'] },
  row: { display: 'flex', gap: space['2'] },
  divider: { height: '1px', background: color.border, margin: `${space['3']} 0` },
  field: { display: 'flex', flexDirection: 'column', gap: space['1'] },
  label: {
    fontSize: fontSize['12'],
    color: color.subtext,
    fontWeight: fontWeight.medium,
  },
  input: {
    width: '100%',
    height: '32px',
    padding: `0 ${space['3']}`,
    background: color.mantle,
    color: color.text,
    border: `1px solid ${color.border}`,
    borderRadius: radius.sm,
    fontSize: fontSize['13'],
    fontFamily: 'inherit',
    outline: 'none',
    transition: `border-color ${motion.fast}, background ${motion.fast}`,
  },
  // Korean offers no spaces to wrap on, so without keep-all a hint breaks mid-word
  // ("실행 중" / "인 작업은") and reads as a typo.
  hint: {
    fontSize: fontSize['11'], color: color.muted, marginTop: space['0.5'],
    lineHeight: 1.5, wordBreak: 'keep-all', overflowWrap: 'anywhere',
  },
  error: {
    fontSize: fontSize['12'],
    color: color.danger,
    background: 'rgba(243, 139, 168, 0.08)',
    border: `1px solid rgba(243, 139, 168, 0.18)`,
    borderRadius: radius.sm,
    padding: `${space['2']} ${space['3']}`,
    marginTop: space['2'],
  },
  segment: {
    display: 'flex',
    gap: '2px',
    background: color.crust,
    border: `1px solid ${color.border}`,
    borderRadius: radius.sm,
    padding: '2px',
  },
  segmentBtn: {
    flex: 1,
    height: '26px',
    border: 'none',
    background: 'transparent',
    fontSize: fontSize['12'],
    fontWeight: fontWeight.medium,
    color: color.muted,
    fontFamily: 'inherit',
    cursor: 'pointer',
    borderRadius: radius.xs,
    transition: `background ${motion.fast}, color ${motion.fast}`,
  },
  toggleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: space['3'],
  },
  toggle: {
    position: 'relative',
    width: '30px',
    height: '16px',
    border: 'none',
    borderRadius: radius.full,
    cursor: 'pointer',
    transition: `background ${motion.fast}`,
    padding: 0,
    flexShrink: 0,
  },
  toggleKnob: {
    position: 'absolute',
    top: '2px',
    left: '2px',
    width: '12px',
    height: '12px',
    background: '#fff',
    borderRadius: radius.full,
    transition: `transform ${motion.fast}`,
  },
  footer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: space['1.5'],
    padding: `${space['3']} ${space['4']}`,
    borderTop: `1px solid ${color.border}`,
    background: color.mantle,
  },
};
