/**
 * Terminal 인라인 스타일 모음 + spin keyframes 1회 주입.
 * Terminal.jsx 본체와 TerminalOverlays 가 공용으로 import. 순수 스타일 데이터.
 */
import { tokens } from '../../styles/tokens';

const { fontSize, fontWeight, lineHeight, radius, space } = tokens;

// spin keyframes — 모듈 로드 시 한 번만 주입
(() => {
  if (typeof document === 'undefined') return;
  if (document.getElementById('tl-spin-kf')) return;
  const s = document.createElement('style');
  s.id = 'tl-spin-kf';
  s.textContent = '@keyframes tl-spin{to{transform:rotate(360deg)}}';
  document.head.appendChild(s);
})();

export const styles = {
  statusOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  modalOverlay: (themeUi, zIndex) => ({
    position: 'absolute',
    inset: 0,
    padding: space['3'],
    background: themeUi.scrim,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex,
    backdropFilter: 'blur(2px)',
    WebkitBackdropFilter: 'blur(2px)',
    fontFamily: 'inherit',
  }),
  fixedModalOverlay: (themeUi, zIndex) => ({
    position: 'absolute',
    inset: 0,
    padding: space['3'],
    background: 'rgba(0,0,0,0.38)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex,
    backdropFilter: 'blur(5px)',
    WebkitBackdropFilter: 'blur(5px)',
    fontFamily: 'inherit',
  }),
  modalCard: (themeUi) => ({
    width: '90%',
    maxWidth: '360px',
    maxHeight: '80%',
    background: `color-mix(in srgb, ${themeUi.surface0 || themeUi.base} 82%, transparent)`,
    color: themeUi.text,
    border: `1px solid ${themeUi.borderStrong || themeUi.border}`,
    borderRadius: '12px',
    boxShadow: '0 8px 32px rgba(0,0,0,0.45), inset 0 1px 0 rgba(255,255,255,0.06)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    fontFamily: 'inherit',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
  }),
  modalHeader: (themeUi) => ({
    display: 'flex',
    alignItems: 'center',
    gap: space['3'],
    padding: `${space['4']} ${space['4']} ${space['2']}`,
  }),
  iconTile: (themeUi) => ({
    width: '36px',
    height: '36px',
    borderRadius: '9px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: `color-mix(in srgb, ${themeUi.accent} 18%, transparent)`,
    border: `1px solid color-mix(in srgb, ${themeUi.accent} 40%, transparent)`,
    color: themeUi.accent,
    fontSize: '12px',
    fontWeight: 700,
    flexShrink: 0,
  }),
  glassIconTile: (themeUi, tileColor) => ({
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: `color-mix(in srgb, ${tileColor} 18%, transparent)`,
    border: `1px solid color-mix(in srgb, ${tileColor} 40%, transparent)`,
    color: tileColor,
    flexShrink: 0,
  }),
  glassActionBtn: (themeUi, btnColor) => ({
    width: '100%',
    height: '32px',
    minWidth: 0,
    borderRadius: '7px',
    border: `1px solid color-mix(in srgb, ${btnColor} 60%, transparent)`,
    background: `color-mix(in srgb, ${btnColor} 22%, transparent)`,
    color: btnColor,
    fontSize: fontSize['12'],
    fontWeight: fontWeight.semibold,
    cursor: 'pointer',
    fontFamily: 'inherit',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '5px',
    padding: '0 8px',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
    transition: 'background 120ms',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  }),
  glassActionLabel: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  modalTitle: (themeUi) => ({
    color: themeUi.text,
    fontSize: fontSize['13'],
    fontWeight: fontWeight.semibold,
    letterSpacing: '0.01em',
    flex: 1,
  }),
  modalBody: (themeUi, textAlign = 'center') => ({
    flex: 1,
    padding: `${space['2']} ${space['4']}`,
    color: themeUi.subtext,
    fontSize: fontSize['12'],
    lineHeight: lineHeight.normal,
    textAlign,
    overflow: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: space['2'],
  }),
  modalFooter: (themeUi) => ({
    display: 'flex',
    alignItems: 'center',
    gap: space['2'],
    padding: `${space['3']} ${space['4']} ${space['4']}`,
  }),
  primaryModalButton: (themeUi) => ({
    flex: 1,
    height: '32px',
    borderRadius: '7px',
    border: `1px solid color-mix(in srgb, ${themeUi.accent} 60%, transparent)`,
    background: `color-mix(in srgb, ${themeUi.accent} 22%, transparent)`,
    color: themeUi.accent,
    fontSize: fontSize['12'],
    fontWeight: fontWeight.semibold,
    cursor: 'pointer',
    fontFamily: 'inherit',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
    transition: 'background 120ms',
  }),
  secondaryModalButton: (themeUi) => ({
    flex: 1,
    height: '32px',
    borderRadius: '7px',
    border: `1px solid ${themeUi.border}`,
    background: `color-mix(in srgb, ${themeUi.surface1 || themeUi.surface0} 70%, transparent)`,
    color: themeUi.subtext,
    fontSize: fontSize['12'],
    fontWeight: fontWeight.medium,
    cursor: 'pointer',
    fontFamily: 'inherit',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
    transition: 'background 120ms',
  }),
  promptField: {
    display: 'flex',
    flexDirection: 'column',
    gap: space['1.5'],
  },
  promptLabel: (themeUi) => ({
    fontSize: fontSize['12'],
    color: themeUi.subtext,
  }),
  promptInputRow: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    gap: space['1.5'],
  },
  promptInput: (themeUi) => ({
    flex: 1,
    minWidth: 0,
    height: '38px',
    padding: `0 ${space['3']}`,
    background: `color-mix(in srgb, ${themeUi.mantle || themeUi.base} 80%, transparent)`,
    color: themeUi.text,
    border: `1px solid ${themeUi.borderStrong || themeUi.border}`,
    borderRadius: '7px',
    outline: 'none',
    fontSize: fontSize['14'],
    fontFamily: 'inherit',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
  }),
  inlineBanner: (themeUi, shown = true) => ({
    position: 'absolute',
    bottom: space['2'],
    left: space['2'],
    right: space['2'],
    display: 'flex',
    alignItems: 'center',
    gap: space['2'],
    padding: `${space['1.5']} ${space['3']}`,
    background: `color-mix(in srgb, ${themeUi.surface1 || themeUi.surface0} 75%, transparent)`,
    backdropFilter: 'blur(12px)',
    WebkitBackdropFilter: 'blur(12px)',
    border: `1px solid ${themeUi.borderStrong || themeUi.border}`,
    borderRadius: '8px',
    boxShadow: '0 4px 16px rgba(0,0,0,0.3)',
    zIndex: 12,
    fontSize: fontSize['11'],
    fontFamily: 'inherit',
    // 그레이스풀 페이드 — 팝업처럼 튀지 않고 부드럽게 떴다 사라진다.
    opacity: shown ? 1 : 0,
    transform: shown ? 'translateY(0)' : 'translateY(6px)',
    transition: 'opacity 220ms ease, transform 220ms ease',
    willChange: 'opacity, transform',
  }),
  // 재연결 로딩 pill — 아래쪽 가운데 로딩 스피너 + 짧은 문구. 버튼 없음.
  reconnectPill: (themeUi, shown = true) => ({
    position: 'absolute',
    bottom: space['2'],
    left: '50%',
    display: 'inline-flex',
    alignItems: 'center',
    gap: space['1.5'],
    padding: `${space['1']} ${space['3']}`,
    background: `color-mix(in srgb, ${themeUi.surface1 || themeUi.surface0} 82%, transparent)`,
    backdropFilter: 'blur(12px)',
    WebkitBackdropFilter: 'blur(12px)',
    border: `1px solid ${themeUi.border}`,
    borderRadius: '999px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.22)',
    zIndex: 12,
    fontSize: fontSize['11'],
    fontFamily: 'inherit',
    pointerEvents: 'none',
    maxWidth: 'calc(100% - 16px)',
    whiteSpace: 'nowrap',
    // 짧은 끊김엔 안 뜨고, 길어지면 스르륵 떴다 복구 시 부드럽게 사라진다. (가운데 정렬 유지)
    opacity: shown ? 0.96 : 0,
    transform: shown ? 'translateX(-50%) translateY(0)' : 'translateX(-50%) translateY(6px)',
    transition: 'opacity 240ms ease, transform 240ms ease',
    willChange: 'opacity, transform',
  }),
  reconnectPillText: (themeUi) => ({
    color: themeUi.subtext,
    fontSize: fontSize['11'],
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    letterSpacing: '0.01em',
  }),
  bannerText: (themeUi) => ({
    flex: 1,
    color: themeUi.subtext,
    fontSize: fontSize['11'],
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  }),
  bannerButton: (themeUi) => ({
    height: '22px',
    width: '22px',
    minWidth: '22px',
    padding: 0,
    borderRadius: '5px',
    border: `1px solid color-mix(in srgb, ${themeUi.accent} 60%, transparent)`,
    background: `color-mix(in srgb, ${themeUi.accent} 22%, transparent)`,
    color: themeUi.accent,
    cursor: 'pointer',
    fontFamily: 'inherit',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    boxSizing: 'border-box',
  }),
  promptPasteButton: (themeUi) => ({
    height: '40px',
    padding: `0 ${space['3']}`,
    background: themeUi.surface1,
    color: themeUi.text,
    border: `1px solid ${themeUi.border}`,
    borderRadius: radius.sm,
    fontSize: fontSize['12'],
    fontWeight: fontWeight.medium,
    cursor: 'pointer',
    fontFamily: 'inherit',
  }),
};
