import { tokens } from '../../styles/tokens';
import { glassMenuStyle } from '../../styles/glass';
import { ROW_HEIGHT } from './fileTreeConstants';

const { color, font, fontSize, fontWeight, radius, space, motion } = tokens;

export const styles = {
  wrap: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    background: 'transparent',
    color: color.text,
    fontFamily: font.sans,
    overflow: 'hidden',
  },
  head: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
    padding: `${space['1.5']} ${space['2']} ${space['2']}`,
    borderBottom: `1px solid ${color.border}`,
    gap: '4px',
  },
  virtualSpacer: {
    flexShrink: 0,
    pointerEvents: 'none',
  },
  headTopRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: space['2'],
    minWidth: 0,
    minHeight: '22px',
  },
  headTitle: {
    flex: 1,
    minWidth: 0,
    color: color.text,
    fontSize: fontSize['12'],
    fontWeight: fontWeight.semibold,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  pathRow: {
    minWidth: 0,
    minHeight: '22px',
    display: 'flex',
    alignItems: 'center',
    padding: `0 ${space['1.5']}`,
    background: color.crust,
    border: `1px solid ${color.border}`,
    borderRadius: radius.xs,
  },
  /* The path row is a button so it reads as clickable; it keeps the row's own padding so
     switching to the input does not shift the text by a pixel. */
  pathButton: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    alignItems: 'center',
    background: 'transparent',
    border: 'none',
    padding: 0,
    margin: 0,
    cursor: 'text',
    textAlign: 'left',
    font: 'inherit',
  },
  pathInput: {
    flex: 1,
    minWidth: 0,
    background: 'transparent',
    border: 'none',
    outline: 'none',
    padding: 0,
    color: color.text,
    fontSize: fontSize['11'],
    fontFamily: font.mono,
  },
  branchName: {
    fontSize: fontSize['11'],
    fontFamily: font.mono,
    color: color.subtext,
    lineHeight: '22px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '100%',
    width: '100%',
  },
  countBadge: {
    fontSize: fontSize['11'],
    color: color.accent,
    background: color.accentSubtle,
    border: `1px solid ${color.accentBorder}`,
    borderRadius: radius.full,
    padding: `0 ${space['1.5']}`,
    fontFamily: font.mono,
    flexShrink: 0,
  },
  headActions: {
    display: 'flex',
    gap: '2px',
    alignItems: 'center',
    flexShrink: 0,
  },
  searchBar: {
    display: 'flex',
    alignItems: 'center',
    gap: space['2'],
    minHeight: 0,
    padding: `0 ${space['2']}`,
    boxSizing: 'border-box',
    borderBottom: '1px solid transparent',
    background: 'transparent',
    overflow: 'hidden',
    maxHeight: 0,
    opacity: 0,
    pointerEvents: 'none',
    transition: `max-height ${motion.normal}, opacity ${motion.fast}, padding ${motion.normal}, border-color ${motion.normal}`,
  },
  searchBarOpen: {
    maxHeight: '42px',
    opacity: 1,
    padding: `${space['1.5']} ${space['2']}`,
    borderBottom: `1px solid ${color.border}`,
    pointerEvents: 'auto',
  },
  searchInput: {
    flex: 1,
    height: '26px',
    background: color.crust,
    color: color.text,
    border: `1px solid ${color.border}`,
    borderRadius: radius.xs,
    padding: '0 6px',
    fontSize: fontSize['12'],
    fontFamily: font.sans,
    outline: 'none',
  },
  searchClearBtn: {
    background: 'transparent',
    border: 'none',
    color: color.muted,
    cursor: 'pointer',
    padding: '2px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  transferBar: {
    padding: '6px 8px',
    borderBottom: `1px solid ${color.border}`,
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    minHeight: '26px',
    boxSizing: 'border-box',
  },
  transferTrack: {
    flex: 1,
    height: '4px',
    background: color.surface0,
    borderRadius: '2px',
    overflow: 'hidden',
    minWidth: 0,
  },
  transferFill: {
    height: '100%',
    borderRadius: '2px',
    transition: 'width 0.3s ease, background 0.2s ease',
  },
  transferLabel: {
    fontSize: '10px',
    color: color.subtext,
    whiteSpace: 'nowrap',
    fontFamily: font.sans,
    maxWidth: '54%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  headActionBtn: {
    width: '22px',
    height: '22px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'transparent',
    color: color.muted,
    border: 'none',
    borderRadius: radius.xs,
    cursor: 'pointer',
    transition: `color ${motion.fast}`,
  },
  list: {
    flex: 1,
    overflowY: 'auto',
    padding: `${space['1']} ${space['1']}`,
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    minHeight: '200px',
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '0 4px',
    height: `${ROW_HEIGHT}px`,
    minHeight: `${ROW_HEIGHT}px`,
    borderRadius: radius.xs,
    cursor: 'pointer',
    fontSize: fontSize['13'],
    userSelect: 'none',
    transition: `background ${motion.fast}`,
  },
  chevron: {
    width: '12px',
    height: '12px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: color.muted,
    flexShrink: 0,
  },
  name: {
    flex: 1,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  gitTag: {
    fontSize: fontSize['11'],
    fontFamily: font.mono,
    fontWeight: fontWeight.medium,
    flexShrink: 0,
    minWidth: '14px',
    textAlign: 'right',
    paddingRight: '2px',
  },
  editInput: {
    flex: 1,
    height: '20px',
    background: color.crust,
    color: color.text,
    border: `1px solid ${color.accentBorder}`,
    borderRadius: radius.xs,
    padding: '0 4px',
    fontSize: fontSize['13'],
    fontFamily: 'inherit',
    outline: 'none',
  },
  statusBox: {
    padding: `${space['8']} ${space['4']}`,
    textAlign: 'center',
    color: color.muted,
    fontSize: fontSize['12'],
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
  },
  menu: {
    // 컨텍스트 메뉴 — 현재 포커스 pane 의 테마 따라가도록 var(--ui-*) 사용.
    // (포커스 pane 의 테마가 :root 에 자동 적용 → 포털로 document.body 에 렌더돼도 동작.)
    color: 'var(--ui-text)',
    ...glassMenuStyle({}, { padding: `${space['1']} 0`, borderRadius: radius.md }),
    minWidth: '180px',
    fontFamily: font.sans,
  },
  menuItem: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: space['2'],
    padding: `${space['1.5']} ${space['3']}`,
    background: 'transparent',
    color: 'var(--ui-text)',
    border: 'none',
    cursor: 'pointer',
    fontSize: fontSize['13'],
    fontFamily: 'inherit',
    textAlign: 'left',
    transition: `background ${motion.fast}`,
  },
  errorBox: {
    color: color.danger,
    padding: space['3'],
    fontSize: fontSize['12'],
    display: 'flex',
    flexDirection: 'column',
    gap: space['2'],
    alignItems: 'flex-start',
  },
  retryBtn: {
    background: 'transparent',
    color: color.danger,
    border: `1px solid ${color.danger}55`,
    padding: `${space['1']} ${space['2']}`,
    borderRadius: radius.xs,
    cursor: 'pointer',
    fontSize: fontSize['12'],
  },
};
