import { tokens } from '../../styles/tokens';
import { glassMenuStyle, glassSectionStyle } from '../../styles/glass';

const { color, font, fontSize, fontWeight, radius, space, motion } = tokens;

export const styles = {
  wrap: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
    background: 'transparent',
  },
  head: {
    height: '32px',
    minHeight: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: `0 ${space['2']}`,
    ...glassSectionStyle(),
    borderBottom: `1px solid color-mix(in srgb, var(--ui-border, ${color.border}) 72%, transparent)`,
    gap: space['2'],
  },
  headLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: space['1.5'],
    minWidth: 0,
    flex: 1,
  },
  repoLabel: {
    fontSize: fontSize['12'],
    fontFamily: font.mono,
    fontWeight: fontWeight.medium,
    color: color.text,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  branchName: {
    fontSize: fontSize['12'],
    fontFamily: font.mono,
    color: color.muted,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  countBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '14px',
    minWidth: '14px',
    boxSizing: 'border-box',
    fontSize: '10px',
    lineHeight: 1,
    color: color.muted,
    background: `color-mix(in srgb, var(--ui-crust, ${color.crust}) 58%, transparent)`,
    border: `1px solid color-mix(in srgb, var(--ui-border, ${color.border}) 72%, transparent)`,
    borderRadius: radius.full,
    padding: `0 ${space['1']}`,
    fontFamily: font.mono,
    flexShrink: 0,
  },
  iconBtn: {
    width: '22px',
    height: '22px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'transparent',
    color: color.muted,
    border: 'none',
    borderRadius: radius.xs,
    cursor: 'pointer',
    transition: `color ${motion.fast}`,
  },
  searchBar: {
    display: 'flex',
    alignItems: 'center',
    gap: space['1'],
    padding: `${space['1']} ${space['2']}`,
    borderBottom: `1px solid color-mix(in srgb, var(--ui-border, ${color.border}) 72%, transparent)`,
    background: `color-mix(in srgb, var(--ui-crust, ${color.crust}) 58%, transparent)`,
    minHeight: '28px',
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    height: '20px',
    padding: `0 ${space['1']}`,
    background: 'transparent',
    border: 'none',
    color: color.text,
    fontSize: fontSize['11'],
    fontFamily: font.mono,
    outline: 'none',
  },
  searchClear: {
    width: '18px',
    height: '18px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'transparent',
    color: color.muted,
    border: 'none',
    borderRadius: radius.xs,
    cursor: 'pointer',
    flexShrink: 0,
  },
  commitBar: {
    flexShrink: 0,
    borderBottom: `1px solid color-mix(in srgb, var(--ui-border, ${color.border}) 72%, transparent)`,
    background: `color-mix(in srgb, var(--ui-crust, ${color.crust}) 58%, transparent)`,
    padding: `${space['1.5']} ${space['2']}`,
    display: 'flex',
    flexDirection: 'column',
    gap: space['1'],
  },
  commitRow: {
    display: 'flex',
    alignItems: 'center',
    gap: space['1'],
  },
  commitInput: {
    flex: 1,
    minWidth: 0,
    height: '26px',
    padding: `0 ${space['1.5']}`,
    background: `color-mix(in srgb, var(--ui-surface0, ${color.surface0}) 70%, transparent)`,
    border: `1px solid color-mix(in srgb, var(--ui-border, ${color.border}) 72%, transparent)`,
    borderRadius: radius.sm,
    color: color.text,
    fontSize: fontSize['12'],
    fontFamily: font.sans,
    outline: 'none',
  },
  commitStatus: {
    fontSize: fontSize['11'],
    fontFamily: font.mono,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    opacity: 0.9,
    paddingLeft: '2px',
  },
  actionBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '26px',
    height: '26px',
    flexShrink: 0,
    background: `color-mix(in srgb, var(--ui-surface0, ${color.surface0}) 70%, transparent)`,
    border: `1px solid color-mix(in srgb, var(--ui-border, ${color.border}) 72%, transparent)`,
    borderRadius: radius.sm,
    color: color.subtext,
    cursor: 'pointer',
    transition: `opacity ${motion.fast}, background ${motion.fast}`,
  },
  list: {
    flex: 1,
    overflowY: 'auto',
    padding: `${space['1']} ${space['1']}`,
    minHeight: 0,
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    width: '100%',
    padding: '2px 4px',
    background: 'transparent',
    border: 'none',
    borderRadius: radius.xs,
    cursor: 'pointer',
    fontFamily: 'inherit',
    textAlign: 'left',
    minHeight: '22px',
    transition: `background ${motion.fast}`,
  },
  dirRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '2px 4px',
    background: 'transparent',
    borderRadius: radius.xs,
    cursor: 'pointer',
    minHeight: '22px',
    userSelect: 'none',
    transition: `background ${motion.fast}`,
  },
  dirName: {
    flex: 1,
    fontSize: fontSize['12'],
    color: color.subtext,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  dirCount: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '14px',
    minWidth: '14px',
    boxSizing: 'border-box',
    fontSize: '10px',
    lineHeight: 1,
    color: color.muted,
    background: `color-mix(in srgb, var(--ui-crust, ${color.crust}) 58%, transparent)`,
    border: `1px solid color-mix(in srgb, var(--ui-border, ${color.border}) 72%, transparent)`,
    borderRadius: radius.full,
    padding: `0 ${space['1']}`,
    fontFamily: font.mono,
    flexShrink: 0,
  },
  chevSlot: {
    width: '12px',
    height: '12px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: color.muted,
    flexShrink: 0,
  },
  statusLetter: {
    width: '18px',
    height: '18px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: fontSize['11'],
    fontFamily: font.mono,
    fontWeight: fontWeight.semibold,
    border: '1px solid',
    borderRadius: radius.xs,
    flexShrink: 0,
  },
  name: {
    flex: 1,
    fontSize: fontSize['12'],
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  notice: {
    padding: `${space['6']} ${space['3']}`,
    textAlign: 'center',
    color: color.muted,
  },
  noticeTitle: {
    fontSize: fontSize['12'],
    color: color.subtext,
    marginBottom: space['1'],
  },
  noticeHint: {
    fontSize: fontSize['11'],
    color: color.muted,
  },
  contextMenu: {
    position: 'fixed',
    zIndex: 12000,
    minWidth: '180px',
    padding: '4px',
    ...glassMenuStyle(),
    transition: 'opacity 80ms ease',
  },
  menuItem: {
    width: '100%',
    minHeight: '28px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '0 8px',
    background: 'transparent',
    color: color.subtext,
    border: 'none',
    borderRadius: radius.xs,
    fontFamily: font.sans,
    fontSize: fontSize['12'],
    textAlign: 'left',
    cursor: 'pointer',
  },
  diffOverlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 13000,
    background: 'rgba(0, 0, 0, 0.35)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: space['4'],
  },
  diffModal: {
    width: 'min(920px, 92vw)',
    maxHeight: '82vh',
    display: 'flex',
    flexDirection: 'column',
    ...glassMenuStyle(),
    overflow: 'hidden',
  },
  diffHeader: {
    minHeight: '34px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: space['2'],
    padding: `0 ${space['2']}`,
    borderBottom: `1px solid color-mix(in srgb, var(--ui-border, ${color.border}) 72%, transparent)`,
  },
  diffTitle: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: color.text,
    fontSize: fontSize['12'],
    fontFamily: font.mono,
  },
  diffClose: {
    width: '24px',
    height: '24px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'transparent',
    color: color.muted,
    border: 'none',
    borderRadius: radius.xs,
    cursor: 'pointer',
    flexShrink: 0,
  },
  diffBody: {
    margin: 0,
    padding: space['3'],
    overflow: 'auto',
    color: color.subtext,
    fontFamily: font.mono,
    fontSize: fontSize['11'],
    lineHeight: 1.45,
    whiteSpace: 'pre-wrap',
  },
};
